services:
  squid:
    image: ubuntu/squid
    container_name: squid
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./conf/linux_repos.list:/etc/squid/linux_repos.list
      - ./conf/ms365_oidc_domains.list:/etc/squid/ms365_oidc_domains.list
      - ./conf/ms365_allowed_ips.list:/etc/squid/ms365_allowed_ips.list
      - squid-cache:/var/spool/squid
    command: ["-N"]

volumes:
  squid-cache:
